categories:
  - JEDZENIE
  - NAPOJE
  - ALKOHOL
  - ADMINISTRACYJNE
  - BANK
  - BAR
  - CHEMIA
  - CIASTA
  - DOSTAWY
  - GAZ
  - IMPREZY
  - INNE RACHUNKI
  - KAWA
  - KONCESJA
  - LODY
  - LÓD
  - PODATEK
  - PRĄD
  - REKLAMA
  - REMONT
  - ŚMIECIE
  - UBEZPIECZENIE
  - WODA
  - WYPOSAŻENIE
